"""Initial migration

Revision ID: 5d0385d53f2a
Revises: 
Create Date: 2026-04-02 02:35:46.585786

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0385d53f2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id_route', sa.Integer(), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id_route')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_route_position ON route USING gist (position)")
    op.create_table('bus',
    sa.Column('id_bus', sa.Integer(), nullable=False),
    sa.Column('id_route', sa.Integer(), nullable=False),
    sa.Column('patent', sa.String(length=7), nullable=False),
    sa.Column('identifier', sa.String(length=10), nullable=False),
    sa.Column('company', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_route'], ['route.id_route'], ),
    sa.PrimaryKeyConstraint('id_bus'),
    sa.UniqueConstraint('patent')
    )
    op.create_table('bus_stop',
    sa.Column('id_bus_stop', sa.Integer(), nullable=False),
    sa.Column('id_route', sa.Integer(), nullable=False),
    sa.Column('position', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['id_route'], ['route.id_route'], ),
    sa.PrimaryKeyConstraint('id_bus_stop')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_bus_stop_position ON bus_stop USING gist (position)")
    op.create_table('route_stops',
    sa.Column('id_route', sa.Integer(), nullable=False),
    sa.Column('id_stop', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_route'], ['route.id_route'], ),
    sa.ForeignKeyConstraint(['id_stop'], ['bus_stop.id_bus_stop'], ),
    sa.PrimaryKeyConstraint('id_route', 'id_stop')
    )
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('route_stops')
    op.drop_index('idx_bus_stop_position', table_name='bus_stop', postgresql_using='gist')
    op.drop_table('bus_stop')
    op.drop_table('bus')
    op.drop_index('idx_route_position', table_name='route', postgresql_using='gist')
    op.drop_table('route')
    # ### end Alembic commands ###
