"""Update Buses

Revision ID: 9318f945e4f0
Revises: ca8785870b4e
Create Date: 2025-12-15 23:40:21.241546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9318f945e4f0'
down_revision: Union[str, Sequence[str], None] = 'ca8785870b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bus', sa.Column('company', sa.String(length=10), nullable=False))
    op.add_column('bus', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bus', 'is_active')
    op.drop_column('bus', 'company')
    # ### end Alembic commands ###
