"""Migracion inicial Bus y Location

Revision ID: ca8785870b4e
Revises: 
Create Date: 2025-12-15 00:46:20.227551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8785870b4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bus', 'patent',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('bus', 'identifier',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bus', 'identifier',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('bus', 'patent',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.drop_table('location')
    # ### end Alembic commands ###
